# Generated by Django 5.2.1 on 2025-05-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name": "News", "verbose_name_plural": "News"},
        ),
        migrations.AlterField(
            model_name="news",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
