# Generated by Django 5.2.1 on 2025-05-25 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_plan_is_pro_user_plan_alter_plan_name_and_more"),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_pro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="news",
            name="vertical",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.vertical",
            ),
        ),
    ]
