# Generated by Django 5.2.1 on 2025-05-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_is_pro_news_vertical"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
    ]
