# Generated by Django 5.2.1 on 2025-05-25 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plan_vertical_userprofile_plan_verticals"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_pro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.plan",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="vertical",
            name="name",
            field=models.CharField(
                choices=[
                    ("power", "Power"),
                    ("taxes", "Taxes"),
                    ("health", "Health"),
                    ("energy", "Energy"),
                    ("labor", "Labor"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
