# Generated by Django 5.2.1 on 2025-05-26 02:22

from django.db import migrations

import accounts.managers


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_plan_is_pro_user_plan_alter_plan_name_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.managers.UserManager()),
            ],
        ),
    ]
