# Generated by Django 5.2.1 on 2025-05-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vertical",
            name="name",
            field=models.CharField(
                choices=[
                    ("poder", "Poder"),
                    ("tributos", "Tributos"),
                    ("saude", "Saúde"),
                    ("energia", "Energia"),
                    ("trabalhista", "Trabalhista"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
