# Generated by Django 5.2.1 on 2025-05-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_vertical_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
