# Generated by Django 5.2.1 on 2025-05-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_plan_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
